name: flutter-test

on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter test
